### ISSUE TITLE
Makefile:41: ターゲット 'Twemoji.tmpl.ttx' のレシピで失敗する

### ISSUE THREAD

**Issue by zer0ohm** [tetsu31415/Twemoji4Android#2]
Android5.1でTwemojiのフォントを使用したいと思い、調べていたところ貴サイト[http://tetsu31415.hatenablog.com/entry/2014/11/22/012845]に辿り着きました。
レポジトリをcloneしてmakeを実行したところ件名の通り「'Twemoji.tmpl.ttx' のレシピで失敗しました」とエラーを吐かれてしまいました。

実行時のログ全文を以下に記します。
``` terminal
$ git clone https://github.com/tetsu31415/Twemoji4Android
$ cd Twemoji4Android
$ make
python ./add_glyphs.py "Twemoji.tmpl.ttx.tmpl" "Twemoji.tmpl.ttx" "./png/"
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'name' table...
Parsing 'post' table...
Looking for images matching './png/*.png'.
Traceback (most recent call last):
  File "./add_glyphs.py", line 98, in <module>
    raise Exception ("No image files found in '%s'." % glb)
Exception: No image files found in './png/*.png'.
Makefile:41: ターゲット 'Twemoji.tmpl.ttx' のレシピで失敗しました
make: *** [Twemoji.tmpl.ttx] エラー 1
```

環境
Bash on Ubuntu 
(Linux <ユーザー名> 4.4.0-17134-Microsoft #285-Microsoft Thu Aug 30 17:31:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux)

インストールしたパッケージ
libharfbuzz-bin 
libcairo2-dev 
libpango1.0-dev 
python-gtk2-dev 
imagemagick
librsvg2-dev

以上です。ご教授の程宜しくお願い致します。

**Comment by tetsu31415** [comment]
shx64a様

発生したエラーですが，pngファイルの生成に失敗しているようです．

手元のUbuntu環境でテストをしてみたところ，Makefile内の拡張変数展開に失敗していました．

正しく展開するためには，makeで使用されるシェルを`/bin/bash`にする必要があります．

Makefileの先頭に
```
SHELL:=/bin/bash
```
を追加するか，make実行時に
```
$ make SHELL:=/bin/bash
```
と実行するとMakefile内のスクリプトが正しく実行されると思います．

再度makeを実行する際は，
```
$ make clean
```
を忘れずに実行してください．

よろしくお願い致します．

**Comment by zer0ohm** [comment]
返信ありがとうございます。make SHELL:=/bin/bashで実行でき、ttfの生成まで漕ぎ着けましたので試しにtwitter/twemojiからv11.2のsvgに差し替えてmake cleanしてから実行したところ、
``` terminal
$ make SHELL:=/bin/bash
# 省略 (PNG生成)
python ./add_glyphs.py "Twemoji.tmpl.ttx.tmpl" "Twemoji.tmpl.ttx" "./png/"
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'name' table...
Parsing 'post' table...
Looking for images matching './png/*.png'.
# 中略 (グリフ追加)
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'GSUB' table...
ttx "Twemoji.tmpl.ttx"
Compiling "Twemoji.tmpl.ttx" to "Twemoji.tmpl.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'name' table...
Parsing 'post' table...
Parsing 'GSUB' table...
Traceback (most recent call last):
  File "/usr/bin/ttx", line 6, in <module>
    ttx.main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttx.py", line 350, in main
    process(jobs, options)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttx.py", line 333, in process
    action(input, output, options)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttx.py", line 249, in ttCompile
    ttf.save(output)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 221, in save
    self._writeTable(tag, writer, done)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 653, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 666, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/_c_m_a_p.py", line 67, in compile
    chunk = table.compile(ttFont)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/_c_m_a_p.py", line 969, in compile
    raise KeyError(name)
KeyError: u'200D'
Makefile:44: ターゲット 'Twemoji.tmpl.ttf' のレシピで失敗しました
make: *** [Twemoji.tmpl.ttf] エラー 1
rm Twemoji.tmpl.ttx
```

となってしまいます。重ね重ねですがご教授の程宜しくお願いします。

**Comment by tetsu31415** [comment]
上記エラーですが，現状のプログラムでは古い絵文字フォントの生成には対応していますが，
新しい絵文字には仕様変更などがあり，対応していないようです．

根本的に解決するためにはプログラムを修正する必要があります．
申し訳ありませんが，今は時間が取れずすぐに対応できません．

これは別の問題なので，ここでissueをクローズさせていただきます．
